using System.ComponentModel.DataAnnotations;

namespace tawasal.Model
{
	public class UserFullModel
	{
		public string Id { get; set; }
		public string Title { get; set; }
		public string FirstName { get; set; }
		public string LastName { get; set; }
		public string Gender { get; set; }
		public string Email { get; set; }
		public string DateOfBirth { get; set; }
		public string RegisteredDate { get; set; }
		public string Phone { get; set; }
		public string Picture { get; set; }
		public LocationModel Location { get; set; }
	}

	/*
{
id: string(autogenerated)
title: string("mr", "ms", "mrs", "miss", "dr", "")
firstName: string(length: 2-50)
lastName: string(length: 2-50)
gender: string("male", "female", "other", "")
email: string(email)
dateOfBirth: string(ISO Date - value: 1/1/1900 - now)
registerDate: string(autogenerated)
phone: string(phone number - any format)
picture: string(url)
location: object(Location)
}
	 * */

	public class UserServiceData
	{
		public UserPreviewModel[] data { get; set; }
		public int total { get; set; }
		public int page { get; set; }
		public int limit { get; set; }
	}

	public class UserPreviewModel
	{
		[Required]
		public string id { get; set; }
		public string title { get; set; }
		[Required]
		[StringLength(50, ErrorMessage = "Too long user first name.")]
		public string firstName { get; set; }
		[StringLength(50, ErrorMessage = "Too long user last name")]
		public string lastName { get; set; }
		public string picture { get; set; }
	}


//	{
//id: string (autogenerated)
// title: string ("mr", "ms", "mrs", "miss", "dr", "")
//firstName: string (length: 2-50)
//lastName: string (length: 2-50)
//picture: string (url)
//}

}
